
language: python

python:
  - 3.6

services: postgresql

env:
  - DJANGO=2.1.7

before_install:
  - export DJANGO_SETTINGS_MODULE=krakenes.settings
  - export PYTHONPATH=$HOME/builds/haavardnk/krakenes.com
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py migrate
