language: python
python:
- 3.6
addons:
  postgresql: "9.6"
services:
- docker
env:
- DJANGO=3.0.3
before_install:
- export DJANGO_SETTINGS_MODULE=krakenes.settings
- export PYTHONPATH=$HOME/builds/haavardnk/krakenes.com
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install coverage
- pip install codecov
before_script:
- psql -c "CREATE DATABASE mydb;" -U postgres
script:
- coverage run --source='.' manage.py test
after_success:
- codecov

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
