language: python
python:
- 3.6
addons:
  postgresql: "9.6"

env:
- DJANGO=2.1.7
before_install:
- openssl aes-256-cbc -K $encrypted_cd14369c0037_key -iv $encrypted_cd14369c0037_iv
  -in .travis/id_rsa.enc -out ~/.travis/id_rsa -d
- export DJANGO_SETTINGS_MODULE=krakenes.settings
- export PYTHONPATH=$HOME/builds/haavardnk/krakenes.com
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install coverage
- pip install codecov
before_script:
- psql -c "CREATE DATABASE mydb;" -U postgres
script:
- coverage run --source='.' manage.py test
after_success:
- codecov
- bash .travis/deploy.sh
